### ISSUE TITLE
QEMU i6400-mips64r6-PRIP4 branch hangs when kernel is built with compact branches

### ISSUE THREAD

**Issue by hwoarang** [prplfoundation/qemu#29]
Hi,

I am using the i6400-mips64r6-PRIP4 branch for the Linux kernel R6 bring up and I noticed that when I build the kernel with compact branches, then QEMU hangs (not dead, just seems to spin indefinitely).
I have already provided testing kernel images to the QEMU team. The problem goes away if I build the kernel with -mcompact-branches=never.

**Comment by lalrae** [comment]
Fix got merged to PRIP4 branch thus closing the issue.
