### ISSUE TITLE
MIPS P5600: no error when executing unimplemented Paired-Single instructions

### ISSUE THREAD

**Issue by rdsk** [prplfoundation/qemu#42]
According to [1], Paired-Single instructions are not implemented in MIPS P5600, however, it is still possible to execute them with P5600 CPU defininition without any errors.

Step to reproduce:
```
$ cat t.c
int main () {
    asm volatile ("pll.ps $f2,$f4,$f6");
    return 0;
}
$ mips64el-linux-gnu -mips32r5 -mabi=32 -mfp64 t.c -o t.exe 
$ qemu-mipsel -cpu P5600 t.exe
<returns 0>
```
Tested on i6400-mips64r6-PRIP4 branch.

References:
[1] "P5600 Multiprocessing System Software User's Manual", p646, http://www.imgtec.com/mips/docs/p-class/MD01025-2B-P5600-SUM-01.30.pdf

**Comment by yongbok** [comment]
Fix has been applied. Closing the issue.
