### ISSUE TITLE
Supporting VInt in more models

### ISSUE THREAD

**Issue by mfortune** [prplfoundation/qemu#55]
The M14K has support for vectored interrupts turned on and a number of other cores listed in qemu do include vectored interrupt support in real life.
Please could you enable VInt for at least:
I6400
P5600
mips32r6-generic
MIPS64R2-generic

This means there are example 32-bit and 64-bit cores for R2 and R6 with vectored interrupt support. The latest HAL work from Imagination in the Codescape GNU Tools for MIPS sets up interrupt handling on the assumption that vectored interrupt mode is pretty much commonly available. This is true except for in the qemu simulations of cores.

Simply putting the VINT bit in config3 for these cores at least makes a basic software interrupt test work so the framework in qemu to support this seems to work to some extent.

thanks,
Matthew

**Comment by lalrae** [comment]
VInt support received some bug fixes and VInt bit is now enabled in I6400, P5600, mips32r6-generic and MIPS64R2-generic cores on PRIP5.
